workflows:
  android_release:
    name: "Verum Omnis — Android Release"
    max_build_duration: 45
    instance_type: "linux_x2"

    environment:
      vars:
        JAVA_VERSION: 17
        NODE_VERSION: 20
        ANDROID_SDK_ROOT: "/opt/android-sdk-linux"

    cache:
      cache_paths:
        - "~/.gradle/caches"
        - "~/.gradle/wrapper"
        - "~/.npm"
        - "node_modules"
        - "**/android/.gradle"

    scripts:
      - name: "Set up Node.js"
        script: |
          source ~/.bashrc || true
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v && npm -v

      - name: "Install dependencies"
        script: npm install

      - name: "Sync Capacitor (optional)"
        script: npx cap sync android || echo "No Capacitor project — continuing"

      - name: "Force Java 17 by patching Gradle files (no heredocs)"
        script: |
          # Find probable android dir (root or one level down)
          ANDROID_DIR=$(find . -maxdepth 2 -type d -name android | head -n1 || true)
          if [ -z "$ANDROID_DIR" ]; then
            echo "⚠️  No android/ directory found. Skipping Java patch."
          else
            echo "Android directory: $ANDROID_DIR"
            FILES=$(git ls-files "$ANDROID_DIR/**/build.gradle" "$ANDROID_DIR/**/build.gradle.kts" 2>/dev/null || true)
            if [ -z "$FILES" ]; then
              echo "No Gradle build files to patch."
            else
              echo "$FILES" | xargs -r sed -i -E \
                -e 's/JavaVersion\.VERSION_21/JavaVersion.VERSION_17/g' \
                -e 's/JavaLanguageVersion\.of\(21\)/JavaLanguageVersion.of(17)/g' \
                -e 's/\brelease\s*=\s*21\b/release = 17/g' \
                -e 's/jvmTarget\s*=\s*["'\'']21["'\'']/jvmTarget = "17"/g'
            fi
            chmod +x "$ANDROID_DIR/gradlew" 2>/dev/null || true
          fi

      - name: "Build APK (debug)"
        script: |
          ANDROID_DIR=$(find . -maxdepth 2 -type d -name android | head -n1 || true)
          if [ -n "$ANDROID_DIR" ]; then
            cd "$ANDROID_DIR"
            ./gradlew --no-daemon clean assembleDebug
          else
            echo "❌ No android project found to build." && exit 1
          fi

      - name: "List outputs"
        script: |
          find . -type f \( -name "*.apk" -o -name "*.aab" \) -print || true

    artifacts:
      - "**/build/outputs/**/*.apk"
      - "**/build/outputs/**/*.aab"
      - "**/build/reports/**"

    publishing:
      email:
        recipients:
          - "liam@verumglobal.foundation"
        notify:
          success: true
          failure: true