workflows:
  android_release:
    name: Verum Omnis — Fast APK
    instance_type: linux_x2
    max_build_duration: 45

    scripts:
      - name: Build & package Android
        script: |
          set -euo pipefail
          echo "== 0) Dummy signing =="
          mkdir -p android
          keytool -genkey -v -keystore android/verum-dummy.jks -storepass Verum123! -keypass Verum123! \
            -alias verum -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Verum, OU=Omnis, O=Foundation, L=Global, ST=World, C=AI"

          echo "== 1) Install deps =="
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps

          echo "== 2) Install Capacitor Android =="
          npm install @capacitor/core @capacitor/cli @capacitor/android --legacy-peer-deps

          echo "== 3) Build web app =="
          npm run build || npx vite build || true
          rm -rf www
          [ -d dist ] && cp -r dist www || mkdir -p www && echo '<h1>Verum</h1>' > www/index.html
          echo '{"webDir":"www"}' > capacitor.config.json

          echo "== 4) Capacitor sync =="
          npx cap add android || echo "android already added"
          npx cap sync android

          echo "== 5) Build APK =="
          cd android
          chmod +x gradlew || true
          ./gradlew assembleDebug --no-daemon --stacktrace
          mkdir -p ../build_output
          find app/build/outputs -name "*.apk" -exec cp {} ../build_output/ \;
          ls -lh ../build_output

    artifacts:
      - build_output/**/*.apk