workflows:
  build_android_debug:
    name: Build Android Debug APK
    instance_type: linux_x2
    max_build_duration: 45

    environment:
      vars:
        ANDROID_SDK_ROOT: /usr/local/share/android-sdk
        JAVA_VERSION: 17
        NODE_VERSION: 20

    scripts:
      - name: Setup Node
        script: |
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          npm ci

      - name: Sync Capacitor (if present)
        script: |
          npx cap sync android || true

      - name: Create Java 17 override
        script: |
          cat > java17.init.gradle <<'GROOVY'
          import org.gradle.api.tasks.compile.JavaCompile
          allprojects {
            tasks.withType(JavaCompile).configureEach { jc ->
              jc.sourceCompatibility = JavaVersion.VERSION_17
              jc.targetCompatibility = JavaVersion.VERSION_17
              if (jc.options.hasProperty('release')) jc.options.release = 17
            }
            tasks.matching { it.name.toLowerCase().contains('kotlin') }.configureEach { t ->
              if (t.hasProperty('kotlinOptions')) t.kotlinOptions.jvmTarget = '17'
            }
          }
          GROOVY

      - name: Build APK (debug)
        script: |
          cd android
          chmod +x gradlew
          ./gradlew --no-daemon -I ../java17.init.gradle clean assembleDebug

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - liam@verumglobal.foundation
        notify:
          success: true
          failure: true