workflows:
  android_release_signed:
    name: Android Release (Signed + optional Play upload)
    instance_type: linux_x2
    max_build_duration: 45

    environment:
      vars:
        ANDROID_SDK_ROOT: /usr/local/share/android-sdk
        JAVA_VERSION: 17
        NODE_VERSION: 20
        PLAY_UPLOAD: "false" # change to "true" if you want to upload automatically

      android_signing:
        - MyPlayKeystore

    cache:
      cache_paths:
        - "~/.gradle/wrapper"
        - "~/.gradle/caches"
        - "~/.npm"
        - "node_modules"
        - "android/.gradle"

    scripts:
      - name: Setup Node
        script: |
          source ~/.bashrc || true
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v && npm -v

      - name: Install dependencies
        script: npm install

      - name: Build web & sync Capacitor
        script: |
          npm run build || echo "no web build"
          npx cap sync android || echo "no capacitor"

      - name: Create Java 17 override (Gradle init script)
        script: |
          cat > java17.init.gradle <<'GROOVY'
          import org.gradle.api.tasks.compile.JavaCompile
          import org.jetbrains.kotlin.gradle.tasks.KotlinCompile
          allprojects { proj ->
            ['com.android.application','com.android.library','com.android.test'].each { pid ->
              proj.plugins.withId(pid) {
                def android = proj.extensions.findByName('android')
                if (android != null) {
                  android.compileOptions {
                    sourceCompatibility = JavaVersion.VERSION_17
                    targetCompatibility = JavaVersion.VERSION_17
                  }
                }
              }
            }
            proj.tasks.withType(JavaCompile).configureEach {
              sourceCompatibility = JavaVersion.VERSION_17
              targetCompatibility = JavaVersion.VERSION_17
            }
            proj.tasks.withType(KotlinCompile).configureEach {
              kotlinOptions.jvmTarget = '17'
            }
          }
          GROOVY

      - name: Build Release (APK + AAB)
        script: |
          cd android
          chmod +x gradlew || true
          ./gradlew --no-daemon -I ../java17.init.gradle clean assembleRelease bundleRelease

      - name: List outputs
        script: |
          echo "== APKs ==" && find android/app/build/outputs -name "*.apk" -print || true
          echo "== AABs ==" && find android/app/build/outputs -name "*.aab" -print || true

      - name: Optional Play upload
        script: |
          if [ "$PLAY_UPLOAD" = "true" ]; then
            echo "Would upload AAB via Codemagic Play integration."
          else
            echo "Skipping Play upload (PLAY_UPLOAD=false)"
          fi

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/mapping/**/mapping.txt
      - android/build/reports/**

    publishing:
      email:
        recipients:
          - liam@verumglobal.foundation
        notify:
          success: true
          failure: true