- name: Create Java 17 override (Gradle init script)
  script: |
    cat > java17.init.gradle <<'GROOVY'
    import org.gradle.api.tasks.compile.JavaCompile
    import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

    allprojects { proj ->
      // Use Java 17 toolchain wherever possible
      proj.plugins.withId('java') {
        proj.extensions.getByType(JavaPluginExtension).toolchain {
          languageVersion = JavaLanguageVersion.of(17)
        }
      }

      // Android plugins: set compileOptions 17
      ['com.android.application','com.android.library','com.android.test'].each { pid ->
        proj.plugins.withId(pid) {
          def android = proj.extensions.findByName('android')
          if (android != null) {
            android.compileOptions {
              sourceCompatibility = JavaVersion.VERSION_17
              targetCompatibility = JavaVersion.VERSION_17
            }
          }
        }
      }

      // Fallback for plain JavaCompile tasks (NO options.release here)
      proj.tasks.withType(JavaCompile).configureEach {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
      }

      // Kotlin to 17
      proj.tasks.withType(KotlinCompile).configureEach {
        kotlinOptions.jvmTarget = '17'
      }
    }
    GROOVY