workflows:
  android_release_signed:
    name: Android Release (Signed, JDK21)
    instance_type: linux_x2
    max_build_duration: 45

    environment:
      vars:
        ANDROID_SDK_ROOT: /usr/local/share/android-sdk
        JAVA_VERSION: 21
        NODE_VERSION: 20
      android_signing:
        - MyPlayKeystore   # match the keystore name in Codemagic UI

    cache:
      cache_paths:
        - "~/.gradle/wrapper"
        - "~/.gradle/caches"
        - "~/.npm"
        - "node_modules"
        - "android/.gradle"

    scripts:
      - name: Setup Node
        script: |
          source ~/.bashrc || true
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v && npm -v

      - name: Install dependencies
        script: npm ci || npm install

      - name: Build web & sync Capacitor
        script: |
          npm run build || echo "No web build"
          npx cap sync android || echo "No capacitor"

      - name: Build Release (APK + AAB)
        script: |
          cd android
          chmod +x gradlew || true
          ./gradlew --no-daemon clean assembleRelease bundleRelease

      - name: List outputs
        script: |
          echo "== APKs ==" && find app/build/outputs -name "*.apk" -print || true
          echo "== AABs ==" && find app/build/outputs -name "*.aab" -print || true

    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/*.aab
      - android/app/build/outputs/mapping/**/mapping.txt
      - android/build/reports/**

    publishing:
      email:
        recipients:
          - liam@verumglobal.foundation
        notify:
          success: true
          failure: true