workflows:
  android_release:
    name: Verum Omnis — Fast APK
    instance_type: linux_x2
    max_build_duration: 45

    scripts:
      - name: Build release APK
        script: |
          set -e

          echo "== 1) Dummy signing =="
          mkdir -p android
          keytool -genkey -v -keystore android/verum-dummy.jks -storepass Verum123! -keypass Verum123! \
            -alias verum -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Verum, OU=Omnis, O=Foundation, L=Global, ST=World, C=AI"
          echo "VOM_KEYSTORE=verum-dummy.jks"        >> android/gradle.properties
          echo "VOM_KEYSTORE_PASSWORD=Verum123!"     >> android/gradle.properties
          echo "VOM_KEY_ALIAS=verum"                 >> android/gradle.properties
          echo "VOM_KEY_PASSWORD=Verum123!"          >> android/gradle.properties

          echo "== 2) Install deps & build web (if present) =="
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          if grep -q '"build":' package.json; then npm run build || true; fi

          echo "== 3) Capacitor add/sync =="
          npm install -g @capacitor/cli
          npx cap add android || echo "android/ already present"
          npx cap sync android

          echo "== 4) Gradle assembleRelease =="
          cd android
          chmod +x gradlew || true
          ./gradlew --no-daemon clean
          ./gradlew --no-daemon :app:assembleRelease --stacktrace --info

          echo "== 5) Show APK path =="
          ls -lh app/build/outputs/apk/release || true
          echo "APK: android/app/build/outputs/apk/release/app-release.apk"

    artifacts:
      - android/app/build/outputs/**/*.apk