- name: Provision keystore
        script: |
          set -e
          if [ -n "$CM_KEYSTORE" ]; then
            echo "$CM_KEYSTORE" | base64 --decode > android/verum-release.jks
            echo "VOM_KEYSTORE=verum-release.jks" >> android/gradle.properties
            echo "VOM_KEYSTORE_PASSWORD=${CM_KEYSTORE_PASSWORD}" >> android/gradle.properties
            echo "VOM_KEY_ALIAS=${CM_KEY_ALIAS}" >> android/gradle.properties
            echo "VOM_KEY_PASSWORD=${CM_KEY_PASSWORD}" >> android/gradle.properties
            echo "✅ Signing properties added"
          else
            echo "❌ CM_KEYSTORE missing"
            exit 1
          fi