echo "== 2) Build web =="
npm run build || npx vite build || true
rm -rf www
[ -d dist ] && cp -r dist www || { mkdir -p www; echo '<h1>Verum</h1>' > www/index.html; }

echo "== 3) Create capacitor.config.json =="
cat > capacitor.config.json <<'EOF'
{
  "appId": "foundation.verum.global",
  "appName": "Verum Omnis",
  "webDir": "www",
  "bundledWebRuntime": false
}
EOF
cat capacitor.config.json

echo "== 4) Create/repair native Android project =="
if [ -d android ] && [ ! -f android/settings.gradle ]; then
  echo "Removing empty android folder..."
  rm -rf android
fi
npx cap add android || echo "android already added"
npx cap sync android