workflows:
  android_release:
    name: Verum Omnis - Android Release
    instance_type: linux_x2
    max_build_duration: 60

    scripts:
      - name: Add Android (Capacitor) & sync
        script: |
          set -e
          echo "Preparing Node environment"
          node -v
          npm -v

          echo "Installing Capacitor CLI and Android dependencies"
          npm install --legacy-peer-deps @capacitor/cli @capacitor/core @capacitor/android

          echo "Checking installed packages"
          npx cap --version

          # If android folder doesn’t exist, add it
          if [ ! -d android ]; then
            echo "No android/ folder found. Adding platform…"
            npx cap add android
          else
            echo "android/ folder exists."
          fi

          echo "Syncing Capacitor"
          npx cap sync android

          echo "Done syncing. Showing android folder contents:"
          ls -la android || true