workflows:
  android_release:
    name: "Verum Omnis — Android Release"
    max_build_duration: 45
    instance_type: "linux_x2"

    environment:
      vars:
        JAVA_VERSION: 17
        NODE_VERSION: 20
        ANDROID_SDK_ROOT: "/opt/android-sdk-linux"
        GRADLE_OPTS: "-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx3g -XX:+UseParallelGC'"

    cache:
      cache_paths:
        - "~/.gradle/caches"
        - "~/.gradle/wrapper"
        - "~/.npm"
        - "android/.gradle"
        - "node_modules"

    scripts:
      - name: "Set up Node.js"
        script: |
          source ~/.bashrc || true
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v && npm -v

      - name: "Install dependencies"
        script: npm install

      - name: "Build web assets"
        script: npm run build || echo "No web build script found"

      - name: "Sync Capacitor (Android)"
        script: npx cap sync android || echo "Capacitor not detected, continuing..."

      - name: "Force Java 17"
        script: |
          cat > android/gradle-java17.gradle <<'EOF'
          allprojects {
            tasks.withType(JavaCompile).configureEach {
              sourceCompatibility = JavaVersion.VERSION_17
              targetCompatibility = JavaVersion.VERSION_17
              if (options.hasProperty("release")) options.release = 17
            }
          }
          subprojects {
            plugins.withId("org.jetbrains.kotlin.android") {
              tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
                kotlinOptions { jvmTarget = "17" }
              }
            }
          }
          EOF
          if ! grep -q "apply from: 'gradle-java17.gradle'" android/build.gradle; then
            sed -i "1i apply from: 'gradle-java17.gradle'" android/build.gradle
          fi
          chmod +x android/gradlew

      - name: "Build unsigned APK/AAB"
        script: |
          cd android
          ./gradlew --no-daemon clean assembleDebug
          cd ..

      - name: "List build outputs"
        script: |
          echo "APK files found:"
          find android/app/build/outputs -name "*.apk" -maxdepth 3 || true
          echo "AAB files found:"
          find android/app/build/outputs -name "*.aab" -maxdepth 3 || true

    artifacts:
      - "android/app/build/outputs/**/*.apk"
      - "android/app/build/outputs/**/*.aab"
      - "android/build/reports/**"

    publishing:
      email:
        recipients:
          - "liam@verumglobal.foundation"
        notify:
          success: true
          failure: true