workflows:
  android_release:
    name: "Verum Omnis — Android Release"
    max_build_duration: 45
    instance_type: "linux_x2"

    environment:
      vars:
        JAVA_VERSION: 17
        NODE_VERSION: 20
        ANDROID_SDK_ROOT: "/opt/android-sdk-linux"
        GRADLE_OPTS: "-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx3g -XX:+UseParallelGC'"

    cache:
      cache_paths:
        - "~/.gradle/caches"
        - "~/.gradle/wrapper"
        - "~/.npm"
        - "**/android/.gradle"
        - "node_modules"

    scripts:
      - name: "Set up Node.js"
        script: |
          source ~/.bashrc || true
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v && npm -v

      - name: "Install dependencies"
        script: npm install

      - name: "Build web assets"
        script: npm run build || echo "No web build step — continuing"

      - name: "Sync Capacitor (Android)"
        script: npx cap sync android || echo "No Capacitor project — continuing"

      - name: "Force Java 17 (safe mode)"
        script: |
          ANDROID_DIR=$(find . -type d -name "android" -maxdepth 2 | head -n1)
          if [ -d "$ANDROID_DIR" ]; then
            echo "Detected Android directory: $ANDROID_DIR"
            cat <<'EOF' > "$ANDROID_DIR/gradle-java17.gradle"
allprojects {
  tasks.withType(JavaCompile).configureEach {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
    if (options.hasProperty("release")) options.release = 17
  }
}
subprojects {
  plugins.withId("org.jetbrains.kotlin.android") {
    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
      kotlinOptions { jvmTarget = "17" }
    }
  }
}
EOF
            if ! grep -q "apply from: 'gradle-java17.gradle'" "$ANDROID_DIR/build.gradle"; then
              sed -i "1i apply from: 'gradle-java17.gradle'" "$ANDROID_DIR/build.gradle"
            fi
            chmod +x "$ANDROID_DIR/gradlew" || true
          else
            echo "⚠️ No android folder detected — skipping Java17 patch"
          fi

      - name: "Build APK"
        script: |
          ANDROID_DIR=$(find . -type d -name "android" -maxdepth 2 | head -n1)
          if [ -d "$ANDROID_DIR" ]; then
            cd "$ANDROID_DIR"
            ./gradlew --no-daemon clean assembleDebug
          else
            echo "⚠️ No android project found to build"
          fi

      - name: "List build outputs"
        script: |
          find . -type f \( -name "*.apk" -o -name "*.aab" \) -print || true

    artifacts:
      - "**/build/outputs/**/*.apk"
      - "**/build/outputs/**/*.aab"
      - "**/build/reports/**"

    publishing:
      email:
        recipients:
          - "liam@verumglobal.foundation"
        notify:
          success: true
          failure: true