workflows:
  build_android:
    name: Verum Omnis Android Build
    instance_type: linux_x2
    max_build_duration: 60
    scripts:
      - name: Add Android (Capacitor) & sync
        script: |
          set -e
          echo "Preparing Node environment"
          node -v
          npm -v

          echo "Installing Capacitor CLI and Android dependencies"
          npm install --legacy-peer-deps @capacitor/cli @capacitor/core @capacitor/android

          echo "Ensuring Android platform exists"
          npx cap add android || echo "Android already added"

          echo "Syncing Capacitor project"
          npx cap sync android