- name: Add Android (Capacitor) & sync
        script: |
          set -e
          echo "Preparing Node environment"
          node -v
          npm -v

          echo "Installing Capacitor CLI and Android dependencies"
          npm install --legacy-peer-deps @capacitor/cli @capacitor/core @capacitor/android

          echo "Ensuring Android platform exists"
          npx cap add android || echo "Android already added"

          echo "Syncing Capacitor project"
          npx cap sync android