workflows:
  android_release:
    name: Verum Omnis — Build APK + AAB (Java 17)
    instance_type: linux_x2
    max_build_duration: 45

    environment:
      java: 17
      vars:
        ANDROID_HOME: /opt/android-sdk
        GRADLE_OPTS: -Xmx4096m

    cache:
      cache_paths:
        - ~/.gradle
        - ~/.npm
        - ~/.cache

    scripts:
      - name: Clean workspace
        script: |
          rm -rf android/build || true
          rm -rf android/app/build || true
          rm -rf node_modules || true
          npm ci

      - name: Build Android release
        script: |
          cd android
          ./gradlew clean
          ./gradlew assembleRelease bundleRelease

      - name: Export artifacts
        script: |
          mkdir -p $CM_BUILD_DIR/build_artifacts
          cp android/app/build/outputs/apk/release/app-release.apk $CM_BUILD_DIR/build_artifacts/ || true
          cp android/app/build/outputs/bundle/release/app-release.aab $CM_BUILD_DIR/build_artifacts/ || true

    artifacts:
      - build_artifacts/*.apk
      - build_artifacts/*.aab

    publishing:
      email:
        recipients:
          - liam@verumglobal.foundation