workflows:
  android_release:
    name: Verum Omnis — Fast APK
    instance_type: linux_x2
    max_build_duration: 45

    scripts:
      - name: Build release APK
        script: |
          set -e
          echo "== 1) Dummy signing =="
          mkdir -p android
          keytool -genkey -v -keystore android/verum-dummy.jks -storepass Verum123! -keypass Verum123! \
            -alias verum -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Verum, OU=Omnis, O=Foundation, L=Global, ST=World, C=AI"

          echo "== 2) Web build =="
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          npm run build || npx vite build || true
          if [ -d "dist" ]; then
            echo "Copying dist → www"
            rm -rf www && cp -r dist www
          fi

          echo "== 3) Capacitor add/sync =="
          npm i -g @capacitor/cli
          npx cap add android || echo "android already added"
          npx cap sync android   # <-- removed --no-interactive

          echo "== 4) Gradle assembleRelease =="
          cd android
          chmod +x gradlew || true
          ./gradlew --no-daemon clean
          ./gradlew --no-daemon :app:assembleRelease --stacktrace --info

          echo "== 5) Artifacts =="
          ls -lh app/build/outputs/apk/release || true
          echo "APK path: android/app/build/outputs/apk/release/app-release.apk"

    artifacts:
      - android/app/build/outputs/**/*.apk