workflows:
  android_release:
    name: Verum Omnis — Android Release (Capacitor)
    max_build_duration: 60
    instance_type: linux_x2

    environment:
      vars:
        PACKAGE_NAME: "com.example.verumomnislegalassistant"
        WEB_DIR: "dist"
        JAVA_VERSION: "17"
      groups:
        - android_signing
        - firebase_config
      cache:
        cache_paths:
          - ~/.gradle/caches
          - ~/.gradle/wrapper
          - $FCI_BUILD_DIR/node_modules
          - $FCI_BUILD_DIR/android/.gradle
          - $FCI_BUILD_DIR/android/app/build

    scripts:
      - name: Prepare toolchain
        script: |
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          java -version
          node --version || true
          npm --version || true

      - name: Install JS deps & build web
        script: |
          npm ci || npm install
          npm run build || npx vite build

      - name: Capacitor Android project
        script: |
          npx cap init "Verum Omnis" "$PACKAGE_NAME" --web-dir="$WEB_DIR" --npm-client npm || true
          npx cap add android || true
          npx cap copy android
          npx cap sync android

      - name: Inject google-services.json
        script: |
          mkdir -p android/app
          echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
          echo "[OK] google-services.json added."

      - name: Wire Google Services Gradle plugin
        script: |
          if ! grep -q "com.google.gms:google-services" android/build.gradle; then
            sed -i "/dependencies[[:space:]]*{/a\        classpath 'com.google.gms:google-services:4.4.2'" android/build.gradle
          fi
          if ! grep -q "com.google.gms.google-services" android/app/build.gradle; then
            printf "\napply plugin: 'com.google.gms.google-services'\n" >> android/app/build.gradle
          fi
          if ! grep -q "firebase-bom" android/app/build.gradle; then
            sed -i "/dependencies[[:space:]]*{/a\    implementation platform('com.google.firebase:firebase-bom:33.5.1')\n    implementation 'com.google.firebase:firebase-common-ktx'" android/app/build.gradle
          fi

      - name: (Optional) Keystore for signing
        script: |
          if [ -n "${CM_KEYSTORE_BASE64:-}" ]; then
            echo "$CM_KEYSTORE_BASE64" | base64 -d > android/app/keystore.jks
            cat > android/key.properties <<'EOF'
storePassword=$CM_Ashbash78
keyPassword=$CM_Ashbash78
keyAlias=$CM_verumomnis
storeFile=keystore.jks
EOF
            echo "[OK] key.properties created."
          else
            echo "[SKIP] No keystore secrets provided."
          fi

      - name: Build APK (release)
        script: |
          cd android
          ./gradlew --no-daemon clean assembleRelease

      - name: Generate checksums & QR
        script: |
          APK=$(find android/app/build/outputs/apk/release -type f -name "*release*.apk" | head -n1)
          mkdir -p artifacts
          cp "$APK" artifacts/app-release.apk
          (cd artifacts && sha512sum app-release.apk | awk '{print $1}' > app-release.sha512)
          (cd artifacts && sha256sum app-release.apk | awk '{print $1}' > app-release.sha256)
          echo '{"url":"","sha512":"'"$(cat artifacts/app-release.sha512)"'"}' > artifacts/qr_payload.json
          sudo apt-get update -y && sudo apt-get install -y qrencode
          qrencode -o artifacts/app-release-qr.png "$(cat artifacts/qr_payload.json)"
          ls -la artifacts

    artifacts:
      - artifacts/app-release.apk
      - artifacts/app-release.sha512
      - artifacts/app-release.sha256
      - artifacts/app-release-qr.png

    publishing:
      email:
        recipients:
          - "liam@verumglobal.foundation"
        notify:
          success: true
          failure: true