workflows:
  android_release:
    name: "Verum Omnis — Android Release"
    max_build_duration: 45
    instance_type: "linux_x2"

    environment:
      vars:
        # Codemagic Linux images use this SDK path
        ANDROID_SDK_ROOT: "/usr/local/share/android-sdk"
        JAVA_VERSION: 17
        NODE_VERSION: 20

    cache:
      cache_paths:
        - "~/.gradle/caches"
        - "~/.gradle/wrapper"
        - "~/.npm"
        - "node_modules"
        - "**/android/.gradle"

    scripts:
      - name: "Set up Node.js"
        script: |
          source ~/.bashrc || true
          nvm install $NODE_VERSION
          nvm use $NODE_VERSION
          node -v && npm -v

      - name: "Install dependencies"
        script: npm install

      - name: "Ensure Android platform exists"
        script: |
          ANDROID_DIR=$(find . -maxdepth 2 -type d -name android | head -n1 || true)
          if [ -z "$ANDROID_DIR" ]; then
            echo "No android/ folder; trying Capacitor..."
            if npx cap --version >/dev/null 2>&1; then
              npx cap add android || true
              npx cap sync android || true
              ANDROID_DIR=$(find . -maxdepth 2 -type d -name android | head -n1 || true)
            fi
          fi
          if [ -z "$ANDROID_DIR" ]; then
            echo "❌ No android project found to build."; exit 1
          fi
          echo "Android directory: $ANDROID_DIR"

      - name: "Create Java 17 override (Gradle init script)"
        script: |
          cat > java17.init.gradle <<'GROOVY'
          import org.gradle.api.tasks.compile.JavaCompile

          allprojects {
            tasks.withType(JavaCompile).configureEach { jc ->
              sourceCompatibility = JavaVersion.VERSION_17
              targetCompatibility = JavaVersion.VERSION_17
              if (jc.options.hasProperty('release')) {
                jc.options.release = 17
              }
            }
            tasks.matching { it.name.toLowerCase().contains('kotlin') }.configureEach { t ->
              if (t.hasProperty('kotlinOptions')) {
                t.kotlinOptions.jvmTarget = '17'
              }
            }
          }
          GROOVY

      - name: "Build APK (debug)"
        script: |
          ANDROID_DIR=$(find . -maxdepth 2 -type d -name android | head -n1)
          cd "$ANDROID_DIR"
          chmod +x gradlew || true
          ./gradlew --no-daemon -I ../java17.init.gradle clean assembleDebug

      - name: "List outputs"
        script: |
          find . -type f \( -name "*.apk" -o -name "*.aab" \) -print || true

    artifacts:
      - "**/build/outputs/**/*.apk"
      - "**/build/outputs/**/*.aab"
      - "**/build/reports/**"

    publishing:
      email:
        recipients:
          - "liam@verumglobal.foundation"
        notify:
          success: true
          failure: true