workflows:
  android_release:
    name: Verum Omnis — Fast APK
    instance_type: linux_x2
    max_build_duration: 45

    scripts:
      - name: Build & package Android
        script: |
          set -euo pipefail

          echo "== 0) Dummy signing =="
          mkdir -p android
          keytool -genkey -v -keystore android/verum-dummy.jks -storepass Verum123! -keypass Verum123! \
            -alias verum -keyalg RSA -keysize 2048 -validity 10000 \
            -dname "CN=Verum, OU=Omnis, O=Foundation, L=Global, ST=World, C=AI"

          echo "== 1) Node deps & Capacitor =="
          npm ci --legacy-peer-deps || npm install --legacy-peer-deps
          npm i -D @capacitor/cli @capacitor/core @capacitor/android --legacy-peer-deps

          echo "== 2) Build web =="
          npm run build || npx vite build || true
          rm -rf www
          [ -d dist ] && cp -r dist www || { mkdir -p www; echo '<h1>Verum</h1>' > www/index.html; }
          printf '{"webDir":"www"}\n' > capacitor.config.json
          cat capacitor.config.json

          echo "== 3) Capacitor add/sync =="
          npx cap add android || echo "android already added"
          npx cap sync android

          echo "== 4) Ensure Gradle wrapper =="
          [ -d android ] || { echo "ERROR: android/ folder missing"; ls -la; exit 1; }
          cd android
          ls -la || true

          if [ ! -f gradlew ]; then
            echo "gradlew missing — trying system Gradle to generate wrapper…"
            if command -v gradle >/dev/null 2>&1; then
              gradle wrapper || true
            fi
          fi

          if [ ! -f gradlew ]; then
            echo "System Gradle not available; downloading Gradle 8.7…"
            cd /tmp
            curl -L -o gradle.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
            unzip -q gradle.zip
            cd - >/dev/null
            /tmp/gradle-8.7/bin/gradle wrapper || true
          fi

          if [ ! -f gradlew ]; then
            echo "FATAL: still no gradlew after all attempts. Android dir tree:"
            find . -maxdepth 3 -type f -o -type d | sed 's#^\./##'
            exit 127
          fi

          echo "== 5) Build APK (debug for simplicity) =="
          chmod +x gradlew
          ./gradlew --no-daemon --version || true
          ./gradlew --no-daemon :app:assembleDebug --stacktrace --info

          echo "== 6) Collect artifacts =="
          mkdir -p ../build_output
          find app/build/outputs -name "*.apk" -exec cp {} ../build_output/ \;
          ls -lh ../build_output || true

    artifacts:
      - build_output/**/*.apk